# Generated by Django 5.2.7 on 2025-11-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
